[package]
name = "fern-labour-workers-shared"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
async-trait.workspace = true
strum.workspace = true
anyhow.workspace = true
tracing.workspace = true
worker.workspace = true

fern-labour-event-sourcing-rs.workspace = true
fern-labour-notifications-shared.workspace = true
